In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Permite mostrar los graficos en el mismo notebook
%matplotlib inline

In [7]:
# Cargar informaci√≥n
data = pd.read_csv('HTRU_2.csv', 
                   header = None, 
                   names = ['MeanIntegratedProfile',
                            'StdIntegratedProfile',
                            'ExcessKurtosisIntegratedProfile',
                            'SkewnessIntegratedProfile',
                            'ManDMSNRCurve',
                            'StdDMSNRCurve',
                            'ExcessKurtosisDMSNRCurve',
                            'SkewnessDMSNRCurve',
                            'Class'])

data.head()

,MeanIntegratedProfile,StdIntegratedProfile,ExcessKurtosisIntegratedProfile,SkewnessIntegratedProfile,ManDMSNRCurve,StdDMSNRCurve,ExcessKurtosisDMSNRCurve,SkewnessDMSNRCurve,Class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [13]:
pd.set_option('display.precision', 2)
data.describe()

,MeanIntegratedProfile,StdIntegratedProfile,ExcessKurtosisIntegratedProfile,SkewnessIntegratedProfile,ManDMSNRCurve,StdDMSNRCurve,ExcessKurtosisDMSNRCurve,SkewnessDMSNRCurve,Class
count,17898.00,17898.00,17898.00,17898.00,17898.00,17898.00,17898.00,17898.00,17898.00
mean,111.08,46.55,0.48,1.77,12.61,26.33,8.30,104.86,0.09
std,25.65,6.84,1.06,6.17,29.47,19.47,4.51,106.51,0.29
min,5.81,24.77,-1.88,-1.79,0.21,7.37,-3.14,-1.98,0.00
25%,100.93,42.38,0.03,-0.19,1.92,14.44,5.78,34.96,0.00
50%,115.08,46.95,0.22,0.20,2.80,18.46,8.43,83.06,0.00
75%,127.09,51.02,0.47,0.93,5.46,28.43,10.70,139.31,0.00
max,192.62,98.78,8.07,68.10,223.39,110.64,34.54,1191.00,1.00

In [9]:
data.dtypes

MeanIntegratedProfile              float64
StdIntegratedProfile               float64
ExcessKurtosisIntegratedProfile    float64
SkewnessIntegratedProfile          float64
ManDMSNRCurve                      float64
StdDMSNRCurve                      float64
ExcessKurtosisDMSNRCurve           float64
SkewnessDMSNRCurve                 float64
Class                                int64
dtype: object